/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StokRouteImport } from './routes/stok'
import { Route as PiutangRouteImport } from './routes/piutang'
import { Route as LaporanRouteImport } from './routes/laporan'
import { Route as KasirRouteImport } from './routes/kasir'
import { Route as IndexRouteImport } from './routes/index'

const StokRoute = StokRouteImport.update({
  id: '/stok',
  path: '/stok',
  getParentRoute: () => rootRouteImport,
} as any)
const PiutangRoute = PiutangRouteImport.update({
  id: '/piutang',
  path: '/piutang',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanRoute = LaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => rootRouteImport,
} as any)
const KasirRoute = KasirRouteImport.update({
  id: '/kasir',
  path: '/kasir',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kasir': typeof KasirRoute
  '/laporan': typeof LaporanRoute
  '/piutang': typeof PiutangRoute
  '/stok': typeof StokRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kasir': typeof KasirRoute
  '/laporan': typeof LaporanRoute
  '/piutang': typeof PiutangRoute
  '/stok': typeof StokRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kasir': typeof KasirRoute
  '/laporan': typeof LaporanRoute
  '/piutang': typeof PiutangRoute
  '/stok': typeof StokRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kasir' | '/laporan' | '/piutang' | '/stok'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kasir' | '/laporan' | '/piutang' | '/stok'
  id: '__root__' | '/' | '/kasir' | '/laporan' | '/piutang' | '/stok'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KasirRoute: typeof KasirRoute
  LaporanRoute: typeof LaporanRoute
  PiutangRoute: typeof PiutangRoute
  StokRoute: typeof StokRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stok': {
      id: '/stok'
      path: '/stok'
      fullPath: '/stok'
      preLoaderRoute: typeof StokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piutang': {
      id: '/piutang'
      path: '/piutang'
      fullPath: '/piutang'
      preLoaderRoute: typeof PiutangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan': {
      id: '/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof LaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasir': {
      id: '/kasir'
      path: '/kasir'
      fullPath: '/kasir'
      preLoaderRoute: typeof KasirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KasirRoute: KasirRoute,
  LaporanRoute: LaporanRoute,
  PiutangRoute: PiutangRoute,
  StokRoute: StokRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
