/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as StokRouteImport } from './routes/stok'
import { Route as PiutangRouteImport } from './routes/piutang'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LaporanRouteImport } from './routes/laporan'
import { Route as KasirRouteImport } from './routes/kasir'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const StokRoute = StokRouteImport.update({
  id: '/stok',
  path: '/stok',
  getParentRoute: () => rootRouteImport,
} as any)
const PiutangRoute = PiutangRouteImport.update({
  id: '/piutang',
  path: '/piutang',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanRoute = LaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => rootRouteImport,
} as any)
const KasirRoute = KasirRouteImport.update({
  id: '/kasir',
  path: '/kasir',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/kasir': typeof KasirRoute
  '/laporan': typeof LaporanRoute
  '/login': typeof LoginRoute
  '/piutang': typeof PiutangRoute
  '/stok': typeof StokRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/kasir': typeof KasirRoute
  '/laporan': typeof LaporanRoute
  '/login': typeof LoginRoute
  '/piutang': typeof PiutangRoute
  '/stok': typeof StokRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/kasir': typeof KasirRoute
  '/laporan': typeof LaporanRoute
  '/login': typeof LoginRoute
  '/piutang': typeof PiutangRoute
  '/stok': typeof StokRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/kasir'
    | '/laporan'
    | '/login'
    | '/piutang'
    | '/stok'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/kasir'
    | '/laporan'
    | '/login'
    | '/piutang'
    | '/stok'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/kasir'
    | '/laporan'
    | '/login'
    | '/piutang'
    | '/stok'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  KasirRoute: typeof KasirRoute
  LaporanRoute: typeof LaporanRoute
  LoginRoute: typeof LoginRoute
  PiutangRoute: typeof PiutangRoute
  StokRoute: typeof StokRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stok': {
      id: '/stok'
      path: '/stok'
      fullPath: '/stok'
      preLoaderRoute: typeof StokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piutang': {
      id: '/piutang'
      path: '/piutang'
      fullPath: '/piutang'
      preLoaderRoute: typeof PiutangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan': {
      id: '/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof LaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasir': {
      id: '/kasir'
      path: '/kasir'
      fullPath: '/kasir'
      preLoaderRoute: typeof KasirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  KasirRoute: KasirRoute,
  LaporanRoute: LaporanRoute,
  LoginRoute: LoginRoute,
  PiutangRoute: PiutangRoute,
  StokRoute: StokRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
